-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/HDLMultipleClock/multiple_clock_ip.vhd
-- Created: 2024-08-26 00:46:40
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: -1
-- Target subsystem base rate: -1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: multiple_clock_ip
-- Source Path: multiple_clock_ip
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY multiple_clock_ip IS
  PORT( IPCORE_CLK                        :   IN    std_logic;  -- ufix1
        IPCORE_RESETN                     :   IN    std_logic;  -- ufix1
        in_rsvd                           :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        valid_in                          :   IN    std_logic;  -- ufix1
        out_rsvd                          :   OUT   std_logic;  -- ufix1
        valid_out                         :   OUT   std_logic  -- ufix1
        );
END multiple_clock_ip;


ARCHITECTURE rtl OF multiple_clock_ip IS

  -- Component Declarations
  COMPONENT multiple_clock_ip_reset_sync
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset_in                        :   IN    std_logic;  -- ufix1
          reset_out                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT multiple_clock_ip_dut
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset_x                         :   IN    std_logic;
          dut_enable                      :   IN    std_logic;  -- ufix1
          in_rsvd                         :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
          valid_in                        :   IN    std_logic;  -- ufix1
          ce_out                          :   OUT   std_logic;  -- ufix1
          out_rsvd                        :   OUT   std_logic;  -- ufix1
          valid_out                       :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : multiple_clock_ip_reset_sync
    USE ENTITY work.multiple_clock_ip_reset_sync(rtl);

  FOR ALL : multiple_clock_ip_dut
    USE ENTITY work.multiple_clock_ip_dut(rtl);

  -- Signals
  SIGNAL reset_x                          : std_logic;
  SIGNAL dut_enable                       : std_logic;  -- ufix1
  SIGNAL reset_cm                         : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL out_rsvd_sig                     : std_logic;  -- ufix1
  SIGNAL valid_out_sig                    : std_logic;  -- ufix1

BEGIN
  u_multiple_clock_ip_reset_sync_inst : multiple_clock_ip_reset_sync
    PORT MAP( clk => IPCORE_CLK,  -- ufix1
              reset_in => reset_cm,  -- ufix1
              reset_out => reset_x
              );

  u_multiple_clock_ip_dut_inst : multiple_clock_ip_dut
    PORT MAP( clk => IPCORE_CLK,  -- ufix1
              reset_x => reset_x,
              dut_enable => dut_enable,  -- ufix1
              in_rsvd => in_rsvd,  -- ufix8
              valid_in => valid_in,  -- ufix1
              ce_out => ce_out_sig,  -- ufix1
              out_rsvd => out_rsvd_sig,  -- ufix1
              valid_out => valid_out_sig  -- ufix1
              );

  dut_enable <= '1';

  reset_cm <=  NOT IPCORE_RESETN;

  out_rsvd <= out_rsvd_sig;

  valid_out <= valid_out_sig;

END rtl;

