#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Aug 25 11:51:50 -03 2024
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L xbip_utils_v3_0_11 -L xbip_pipe_v3_0_7 -L xbip_bram18k_v3_0_7 -L mult_gen_v12_0_19 -L c_reg_fd_v12_0_7 -L c_mux_bit_v12_0_7 -L c_shift_ram_v12_0_15 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot file_tb_behav xil_defaultlib.file_tb xil_defaultlib.glbl -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L xbip_utils_v3_0_11 -L xbip_pipe_v3_0_7 -L xbip_bram18k_v3_0_7 -L mult_gen_v12_0_19 -L c_reg_fd_v12_0_7 -L c_mux_bit_v12_0_7 -L c_shift_ram_v12_0_15 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot file_tb_behav xil_defaultlib.file_tb xil_defaultlib.glbl -log elaborate.log

