-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/hdl_block/my_block_pkg.vhd
-- Created: 2024-04-01 23:07:05
-- 
-- Generated by MATLAB 9.13 and HDL Coder 4.0
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE my_block_pkg IS
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
END my_block_pkg;

