-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/hdlcoder_multi_cycle_path_constraints/example_b_ip_src_Subsystem_tc.vhd
-- Created: 2024-09-14 14:12:57
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: example_b_ip_src_Subsystem_tc
-- Source Path: Subsystem_tc
-- Hierarchy Level: 1
-- 
-- Master clock enable input: clk_enable
-- 
-- enb_150_1_0 : identical to clk_enable
-- enb         : 150x slower than clk with last phase
-- enb_1_1_1   : 150x slower than clk with phase 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY example_b_ip_src_Subsystem_tc IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        enb_150_1_0                       :   OUT   std_logic;
        enb                               :   OUT   std_logic;
        enb_1_1_1                         :   OUT   std_logic
        );
END example_b_ip_src_Subsystem_tc;


ARCHITECTURE rtl OF example_b_ip_src_Subsystem_tc IS

  -- Signals
  SIGNAL count150                         : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL comp_0_tmp                       : std_logic;
  SIGNAL phase_0_tmp                      : std_logic;
  SIGNAL phase_0                          : std_logic;
  SIGNAL enb_1                            : std_logic;
  SIGNAL comp_1_tmp                       : std_logic;
  SIGNAL phase_1_tmp                      : std_logic;
  SIGNAL phase_1                          : std_logic;
  SIGNAL enb_1_1_1_1                      : std_logic;

  ATTRIBUTE keep : boolean;
  ATTRIBUTE mcp_info : string;
  ATTRIBUTE direct_enable : string;

  ATTRIBUTE keep OF phase_0 : SIGNAL IS true;
  ATTRIBUTE mcp_info OF phase_0 : SIGNAL IS "Subsystem_tc.u1_d150_o0";
  ATTRIBUTE keep OF phase_1 : SIGNAL IS true;
  ATTRIBUTE mcp_info OF phase_1 : SIGNAL IS "Subsystem_tc.u1_d150_o1";
  ATTRIBUTE direct_enable OF enb_150_1_0 : SIGNAL IS "yes";
  ATTRIBUTE direct_enable OF enb : SIGNAL IS "yes";
  ATTRIBUTE direct_enable OF enb_1_1_1 : SIGNAL IS "yes";

BEGIN
  enb_150_1_0 <= clk_enable;

  -- Count limited, Unsigned Counter
  --  initial value   = 1
  --  step value      = 1
  --  count to value  = 149
  counter_150_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        count150 <= to_unsigned(16#01#, 8);
      ELSIF clk_enable = '1' THEN
        IF count150 >= to_unsigned(16#95#, 8) THEN 
          count150 <= to_unsigned(16#00#, 8);
        ELSE 
          count150 <= count150 + to_unsigned(16#01#, 8);
        END IF;
      END IF;
    END IF;
  END PROCESS counter_150_process;


  
  comp_0_tmp <= '1' WHEN count150 = to_unsigned(16#95#, 8) ELSE
      '0';

  phase_0_tmp <= comp_0_tmp AND clk_enable;

  phase_delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        phase_0 <= '0';
      ELSIF clk_enable = '1' THEN
        phase_0 <= phase_0_tmp;
      END IF;
    END IF;
  END PROCESS phase_delay_process;


  enb_1 <= phase_0 AND clk_enable;

  enb <= enb_1;

  
  comp_1_tmp <= '1' WHEN count150 = to_unsigned(16#00#, 8) ELSE
      '0';

  phase_1_tmp <= comp_1_tmp AND clk_enable;

  phase_delay_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        phase_1 <= '1';
      ELSIF clk_enable = '1' THEN
        phase_1 <= phase_1_tmp;
      END IF;
    END IF;
  END PROCESS phase_delay_1_process;


  enb_1_1_1_1 <= phase_1 AND clk_enable;

  enb_1_1_1 <= enb_1_1_1_1;

END rtl;

