-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/hdlcoder_multi_cycle_path_constraints/example_b_ip_src_Subsystem_pac.vhd
-- Created: 2024-09-14 14:12:57
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE example_b_ip_src_Subsystem_pac IS
  TYPE vector_of_std_logic_vector32 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(31 DOWNTO 0);
  TYPE vector_of_signed32 IS ARRAY (NATURAL RANGE <>) OF signed(31 DOWNTO 0);
END example_b_ip_src_Subsystem_pac;

