-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/HDLAXI4Stream/external_ports_adder_four_src_four_value_adder_pac.vhd
-- Created: 2024-08-31 12:06:47
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE external_ports_adder_four_src_four_value_adder_pac IS
  TYPE vector_of_unsigned8 IS ARRAY (NATURAL RANGE <>) OF unsigned(7 DOWNTO 0);
END external_ports_adder_four_src_four_value_adder_pac;

