-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/HDLAXI4Stream/external_ports_adder_four_dut.vhd
-- Created: 2024-08-31 12:06:52
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: external_ports_adder_four_dut
-- Source Path: external_ports_adder_four/external_ports_adder_four_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY external_ports_adder_four_dut IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        data_in                           :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        valid_in                          :   IN    std_logic;  -- ufix1
        last_in                           :   IN    std_logic;  -- ufix1
        first_in                          :   IN    std_logic;  -- ufix1
        ce_out                            :   OUT   std_logic;  -- ufix1
        data_out                          :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
        valid_out                         :   OUT   std_logic;  -- ufix1
        ready                             :   OUT   std_logic  -- ufix1
        );
END external_ports_adder_four_dut;


ARCHITECTURE rtl OF external_ports_adder_four_dut IS

  -- Component Declarations
  COMPONENT external_ports_adder_four_src_four_value_adder
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          data_in                         :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
          valid_in                        :   IN    std_logic;  -- ufix1
          last_in                         :   IN    std_logic;  -- ufix1
          first_in                        :   IN    std_logic;  -- ufix1
          ce_out                          :   OUT   std_logic;  -- ufix1
          data_out                        :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
          valid_out                       :   OUT   std_logic;  -- ufix1
          ready                           :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : external_ports_adder_four_src_four_value_adder
    USE ENTITY work.external_ports_adder_four_src_four_value_adder(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL valid_in_sig                     : std_logic;  -- ufix1
  SIGNAL last_in_sig                      : std_logic;  -- ufix1
  SIGNAL first_in_sig                     : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL data_out_sig                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL valid_out_sig                    : std_logic;  -- ufix1
  SIGNAL ready_sig                        : std_logic;  -- ufix1

BEGIN
  u_external_ports_adder_four_src_four_value_adder : external_ports_adder_four_src_four_value_adder
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset_x => reset_x,
              data_in => data_in,  -- ufix8
              valid_in => valid_in_sig,  -- ufix1
              last_in => last_in_sig,  -- ufix1
              first_in => first_in_sig,  -- ufix1
              ce_out => ce_out_sig,  -- ufix1
              data_out => data_out_sig,  -- ufix8
              valid_out => valid_out_sig,  -- ufix1
              ready => ready_sig  -- ufix1
              );

  valid_in_sig <= valid_in;

  last_in_sig <= last_in;

  first_in_sig <= first_in;

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  data_out <= data_out_sig;

  valid_out <= valid_out_sig;

  ready <= ready_sig;

END rtl;

