-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/HDLAXI4Stream/external_ports_adder_four.vhd
-- Created: 2024-08-31 12:06:52
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: -1
-- Target subsystem base rate: -1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: external_ports_adder_four
-- Source Path: external_ports_adder_four
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY external_ports_adder_four IS
  PORT( IPCORE_CLK                        :   IN    std_logic;  -- ufix1
        IPCORE_RESETN                     :   IN    std_logic;  -- ufix1
        data_in                           :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        valid_in                          :   IN    std_logic;  -- ufix1
        last_in                           :   IN    std_logic;  -- ufix1
        first_in                          :   IN    std_logic;  -- ufix1
        data_out                          :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
        valid_out                         :   OUT   std_logic;  -- ufix1
        ready                             :   OUT   std_logic  -- ufix1
        );
END external_ports_adder_four;


ARCHITECTURE rtl OF external_ports_adder_four IS

  -- Component Declarations
  COMPONENT external_ports_adder_four_reset_sync
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset_in                        :   IN    std_logic;  -- ufix1
          reset_out                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT external_ports_adder_four_dut
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset_x                         :   IN    std_logic;
          dut_enable                      :   IN    std_logic;  -- ufix1
          data_in                         :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
          valid_in                        :   IN    std_logic;  -- ufix1
          last_in                         :   IN    std_logic;  -- ufix1
          first_in                        :   IN    std_logic;  -- ufix1
          ce_out                          :   OUT   std_logic;  -- ufix1
          data_out                        :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
          valid_out                       :   OUT   std_logic;  -- ufix1
          ready                           :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : external_ports_adder_four_reset_sync
    USE ENTITY work.external_ports_adder_four_reset_sync(rtl);

  FOR ALL : external_ports_adder_four_dut
    USE ENTITY work.external_ports_adder_four_dut(rtl);

  -- Signals
  SIGNAL reset_x                          : std_logic;
  SIGNAL dut_enable                       : std_logic;  -- ufix1
  SIGNAL reset_cm                         : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL data_out_sig                     : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL valid_out_sig                    : std_logic;  -- ufix1
  SIGNAL ready_sig                        : std_logic;  -- ufix1

BEGIN
  u_external_ports_adder_four_reset_sync_inst : external_ports_adder_four_reset_sync
    PORT MAP( clk => IPCORE_CLK,  -- ufix1
              reset_in => reset_cm,  -- ufix1
              reset_out => reset_x
              );

  u_external_ports_adder_four_dut_inst : external_ports_adder_four_dut
    PORT MAP( clk => IPCORE_CLK,  -- ufix1
              reset_x => reset_x,
              dut_enable => dut_enable,  -- ufix1
              data_in => data_in,  -- ufix8
              valid_in => valid_in,  -- ufix1
              last_in => last_in,  -- ufix1
              first_in => first_in,  -- ufix1
              ce_out => ce_out_sig,  -- ufix1
              data_out => data_out_sig,  -- ufix8
              valid_out => valid_out_sig,  -- ufix1
              ready => ready_sig  -- ufix1
              );

  dut_enable <= '1';

  reset_cm <=  NOT IPCORE_RESETN;

  data_out <= data_out_sig;

  valid_out <= valid_out_sig;

  ready <= ready_sig;

END rtl;

