-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/hdlcoder_multi_cycle_path_constraints/example_a_ip_src_Subsystem_tc.vhd
-- Created: 2024-09-14 13:54:12
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: example_a_ip_src_Subsystem_tc
-- Source Path: Subsystem_tc
-- Hierarchy Level: 1
-- 
-- Master clock enable input: clk_enable
-- 
-- enb_65_1_0  : identical to clk_enable
-- enb         : 65x slower than clk with last phase
-- enb_1_1_1   : 65x slower than clk with phase 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY example_a_ip_src_Subsystem_tc IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        enb_65_1_0                        :   OUT   std_logic;
        enb                               :   OUT   std_logic;
        enb_1_1_1                         :   OUT   std_logic
        );
END example_a_ip_src_Subsystem_tc;


ARCHITECTURE rtl OF example_a_ip_src_Subsystem_tc IS

  -- Signals
  SIGNAL count65                          : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL comp_0_tmp                       : std_logic;
  SIGNAL phase_0_tmp                      : std_logic;
  SIGNAL phase_0                          : std_logic;
  SIGNAL enb_1                            : std_logic;
  SIGNAL comp_1_tmp                       : std_logic;
  SIGNAL phase_1_tmp                      : std_logic;
  SIGNAL phase_1                          : std_logic;
  SIGNAL enb_1_1_1_1                      : std_logic;

BEGIN
  enb_65_1_0 <= clk_enable;

  -- Count limited, Unsigned Counter
  --  initial value   = 1
  --  step value      = 1
  --  count to value  = 64
  counter_65_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        count65 <= to_unsigned(16#01#, 7);
      ELSIF clk_enable = '1' THEN
        IF count65 >= to_unsigned(16#40#, 7) THEN 
          count65 <= to_unsigned(16#00#, 7);
        ELSE 
          count65 <= count65 + to_unsigned(16#01#, 7);
        END IF;
      END IF;
    END IF;
  END PROCESS counter_65_process;


  
  comp_0_tmp <= '1' WHEN count65 = to_unsigned(16#40#, 7) ELSE
      '0';

  phase_0_tmp <= comp_0_tmp AND clk_enable;

  phase_delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        phase_0 <= '0';
      ELSIF clk_enable = '1' THEN
        phase_0 <= phase_0_tmp;
      END IF;
    END IF;
  END PROCESS phase_delay_process;


  enb_1 <= phase_0 AND clk_enable;

  enb <= enb_1;

  
  comp_1_tmp <= '1' WHEN count65 = to_unsigned(16#00#, 7) ELSE
      '0';

  phase_1_tmp <= comp_1_tmp AND clk_enable;

  phase_delay_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        phase_1 <= '1';
      ELSIF clk_enable = '1' THEN
        phase_1 <= phase_1_tmp;
      END IF;
    END IF;
  END PROCESS phase_delay_1_process;


  enb_1_1_1_1 <= phase_1 AND clk_enable;

  enb_1_1_1 <= enb_1_1_1_1;

END rtl;

