-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/HDLAXI4Stream/axi4_stream_adder_four_src_rising_edge1.vhd
-- Created: 2024-08-31 09:58:38
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: axi4_stream_adder_four_src_rising_edge1
-- Source Path: HDLAXI4Stream/four_value_adder/rising_edge1
-- Hierarchy Level: 1
-- Model version: 1.51
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY axi4_stream_adder_four_src_rising_edge1 IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        enb                               :   IN    std_logic;
        in_rising                         :   IN    std_logic;
        out_rising                        :   OUT   std_logic
        );
END axi4_stream_adder_four_src_rising_edge1;


ARCHITECTURE rtl OF axi4_stream_adder_four_src_rising_edge1 IS

  -- Signals
  SIGNAL Delay_out1                       : std_logic;
  SIGNAL NOT_out1                         : std_logic;
  SIGNAL AND_out1                         : std_logic;

BEGIN
  Delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Delay_out1 <= '0';
      ELSIF enb = '1' THEN
        Delay_out1 <= in_rising;
      END IF;
    END IF;
  END PROCESS Delay_process;


  NOT_out1 <=  NOT Delay_out1;

  AND_out1 <= in_rising AND NOT_out1;

  out_rising <= AND_out1;

END rtl;

