-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/HDLAXI4Stream/axi4_stream_adder_four_axi4_stream_slave.vhd
-- Created: 2024-08-31 10:23:40
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: axi4_stream_adder_four_axi4_stream_slave
-- Source Path: axi4_stream_adder_four/axi4_stream_adder_four_axi4_stream_slave
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY axi4_stream_adder_four_axi4_stream_slave IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        enb                               :   IN    std_logic;
        AXI4_Stream_Slave_TDATA           :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        AXI4_Stream_Slave_TVALID          :   IN    std_logic;  -- ufix1
        AXI4_Stream_Slave_TLAST           :   IN    std_logic;  -- ufix1
        user_ready                        :   IN    std_logic;  -- ufix1
        AXI4_Stream_Slave_TREADY          :   OUT   std_logic;  -- ufix1
        user_data                         :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
        user_valid                        :   OUT   std_logic;  -- ufix1
        user_TLAST                        :   OUT   std_logic  -- ufix1
        );
END axi4_stream_adder_four_axi4_stream_slave;


ARCHITECTURE rtl OF axi4_stream_adder_four_axi4_stream_slave IS

  -- Component Declarations
  COMPONENT axi4_stream_adder_four_fifo_data
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_rsvd                         :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
          Push                            :   IN    std_logic;  -- ufix1
          Pop                             :   IN    std_logic;  -- ufix1
          Out_rsvd                        :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
          Empty                           :   OUT   std_logic;  -- ufix1
          Full                            :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT axi4_stream_adder_four_fifo_TLAST
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_rsvd                         :   IN    std_logic;  -- ufix1
          Push                            :   IN    std_logic;  -- ufix1
          Pop                             :   IN    std_logic;  -- ufix1
          Out_rsvd                        :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : axi4_stream_adder_four_fifo_data
    USE ENTITY work.axi4_stream_adder_four_fifo_data(rtl);

  FOR ALL : axi4_stream_adder_four_fifo_TLAST
    USE ENTITY work.axi4_stream_adder_four_fifo_TLAST(rtl);

  -- Signals
  SIGNAL fifo_rd_ack                      : std_logic;  -- ufix1
  SIGNAL stream_in_fifo_user_data         : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL fifo_empty                       : std_logic;  -- ufix1
  SIGNAL fifo_full                        : std_logic;  -- ufix1
  SIGNAL fifo_empty_neg                   : std_logic;  -- ufix1
  SIGNAL stream_in_user_valid             : std_logic;  -- ufix1

BEGIN
  u_axi4_stream_adder_four_fifo_data_inst : axi4_stream_adder_four_fifo_data
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb => enb,
              In_rsvd => AXI4_Stream_Slave_TDATA,  -- ufix8
              Push => AXI4_Stream_Slave_TVALID,  -- ufix1
              Pop => fifo_rd_ack,  -- ufix1
              Out_rsvd => stream_in_fifo_user_data,  -- ufix8
              Empty => fifo_empty,  -- ufix1
              Full => fifo_full  -- ufix1
              );

  u_axi4_stream_adder_four_fifo_TLAST_inst : axi4_stream_adder_four_fifo_TLAST
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb => enb,
              In_rsvd => AXI4_Stream_Slave_TLAST,  -- ufix1
              Push => AXI4_Stream_Slave_TVALID,  -- ufix1
              Pop => fifo_rd_ack,  -- ufix1
              Out_rsvd => user_TLAST  -- ufix1
              );

  intdelay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        fifo_rd_ack <= '0';
      ELSIF enb = '1' THEN
        fifo_rd_ack <= user_ready;
      END IF;
    END IF;
  END PROCESS intdelay_process;


  AXI4_Stream_Slave_TREADY <=  NOT fifo_full;

  fifo_empty_neg <=  NOT fifo_empty;

  stream_in_user_valid <= fifo_empty_neg AND fifo_rd_ack;

  user_data <= stream_in_fifo_user_data;

  user_valid <= stream_in_user_valid;

END rtl;

