-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/minimalIpCore/minimal_ip_dut.vhd
-- Created: 2024-08-25 17:48:01
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: minimal_ip_dut
-- Source Path: minimal_ip/minimal_ip_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY minimal_ip_dut IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        in_a                              :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        in_b                              :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        ce_out                            :   OUT   std_logic;  -- ufix1
        a_times_b                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
        a_plus_b                          :   OUT   std_logic_vector(8 DOWNTO 0)  -- ufix9
        );
END minimal_ip_dut;


ARCHITECTURE rtl OF minimal_ip_dut IS

  -- Component Declarations
  COMPONENT minimal_ip_src_minimal_IP
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          in_a                            :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
          in_b                            :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
          ce_out                          :   OUT   std_logic;  -- ufix1
          a_times_b                       :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          a_plus_b                        :   OUT   std_logic_vector(8 DOWNTO 0)  -- ufix9
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : minimal_ip_src_minimal_IP
    USE ENTITY work.minimal_ip_src_minimal_IP(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL a_times_b_sig                    : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL a_plus_b_sig                     : std_logic_vector(8 DOWNTO 0);  -- ufix9

BEGIN
  u_minimal_ip_src_minimal_IP : minimal_ip_src_minimal_IP
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset_x => reset_x,
              in_a => in_a,  -- ufix8
              in_b => in_b,  -- ufix8
              ce_out => ce_out_sig,  -- ufix1
              a_times_b => a_times_b_sig,  -- ufix16
              a_plus_b => a_plus_b_sig  -- ufix9
              );

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  a_times_b <= a_times_b_sig;

  a_plus_b <= a_plus_b_sig;

END rtl;

