-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/HDLMultipleClock/aaa_ip_dut.vhd
-- Created: 2024-09-14 12:45:30
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: aaa_ip_dut
-- Source Path: aaa_ip/aaa_ip_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY aaa_ip_dut IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        in_rsvd                           :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        valid_in                          :   IN    std_logic;  -- ufix1
        ce_out                            :   OUT   std_logic;  -- ufix1
        out_rsvd                          :   OUT   std_logic;  -- ufix1
        valid_out                         :   OUT   std_logic  -- ufix1
        );
END aaa_ip_dut;


ARCHITECTURE rtl OF aaa_ip_dut IS

  -- Component Declarations
  COMPONENT aaa_ip_src_multiple_clock
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          in_rsvd                         :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
          valid_in                        :   IN    std_logic;  -- ufix1
          ce_out                          :   OUT   std_logic;  -- ufix1
          out_rsvd                        :   OUT   std_logic;  -- ufix1
          valid_out                       :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : aaa_ip_src_multiple_clock
    USE ENTITY work.aaa_ip_src_multiple_clock(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL valid_in_sig                     : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL out_rsvd_sig                     : std_logic;  -- ufix1
  SIGNAL valid_out_sig                    : std_logic;  -- ufix1

BEGIN
  u_aaa_ip_src_multiple_clock : aaa_ip_src_multiple_clock
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset_x => reset_x,
              in_rsvd => in_rsvd,  -- ufix8
              valid_in => valid_in_sig,  -- ufix1
              ce_out => ce_out_sig,  -- ufix1
              out_rsvd => out_rsvd_sig,  -- ufix1
              valid_out => valid_out_sig  -- ufix1
              );

  valid_in_sig <= valid_in;

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  out_rsvd <= out_rsvd_sig;

  valid_out <= valid_out_sig;

END rtl;

